[build]
command = "yarn run build"
functions = ".netlify/functions"
publish = "public/"

[[redirects]]
force = true
from = "https://give.pathwaymarietta.com"
status = 302
to = "https://pathwaymarietta.churchcenter.com/giving?open-in-church-center-modal=true"

[[redirects]]
force = true
from = "https://messages.pathwaymarietta.com"
status = 302
to = "https://pathwaymarietta.com/messages"

[[redirects]]
force = true
from = "https://resources.pathwaymarietta.com"
status = 302
to = "https://pathwaymarietta.com/resources"

[[redirects]]
force = true
from = "https://connect.pathwaymarietta.com"
status = 302
to = "https://pathwaymarietta.churchcenter.com/people/forms/125762"

[[redirects]]
force = true
from = "https://groups.pathwaymarietta.com"
status = 302
to = "https://pathwaymarietta.churchcenter.com/groups/connect-groups"

[[redirects]]
force = true
from = "https://merch.pathwaymarietta.com"
status = 302
to = "https://pathway-community-church.myshopify.com/collections/all"

[[redirects]]
force = true
from = "https://about.pathwaymarietta.com"
status = 302
to = "https://pathwaymarietta.com"

[[redirects]]
force = true
from = "https://events.pathwaymarietta.com"
status = 302
to = "https://pathwaymarietta.com/about/events"

[[redirects]]
force = true
from = "https://sg.pathwaymarietta.com"
status = 302
to = "https://pathwaymarietta.com/resources/spiritual-gifts"

[[redirects]]
force = true
from = "https://mb.pathwaymarietta.com"
status = 302
to = "https://pathwaymarietta.com/resources/mbti"

[[redirects]]
force = true
from = "https://eg.pathwaymarietta.com"
status = 302
to = "https://pathwaymarietta.com/resources/enneagram"

[[redirects]]
force = true
from = "https://pathwaymarietta.com/start"
status = 301
to = "https://pathwaymarietta.com/take-a-step"

[[redirects]]
force = true
from = "https://serve.pathwaymarietta.com"
status = 302
to = "https://pathwaymarietta.churchcenter.com/people/forms/175342"

[[redirects]]
force = true
from = "https://checkin.pathwaymarietta.com"
status = 302
to = "https://pathwaymarietta.churchcenter.com/people/forms/122952"

[[redirects]]
force = true
from = "https://ask.pathwaymarietta.com"
status = 302
to = "https://pathwaymarietta.com/ask"

[[redirects]]
force = true
from = "https://movies.pathwaymarietta.com"
status = 302
to = "https://pathwaymarietta.online.church/"

[[redirects]]
force = true
from = "https://women.pathwaymarietta.com"
status = 302
to = "https://pathwaymarietta.churchcenter.com/people/forms/213414"

[[redirects]]
force = true
from = "https://kids.pathwaymarietta.com"
status = 302
to = "https://pathwaymarietta.churchcenter.com/people/forms/214358"
